version: '3.8'

services:
  laravel:
    build:
      context: ./server
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production 
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./database:/var/www/html/database

  react:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - laravel
